version: '3.8'
services:
  api:
    container_name: api
    image: megafair/api:1.0-SNAPSHOT
    ports:
      - '8081:8081'
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/hibernate_db
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
    extra_hosts:
      - "host.docker.internal:host-gateway"
  jwt-auth:
    container_name: jwt-auth
    image: megafair/jwt-auth:1.0-SNAPSHOT
    ports:
      - '8082:8082'
    environment:
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt